name: cinemood
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutter_emoji: ^2.0.0
  dio:
  bloc:
  rxdart:
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  cloud_firestore:
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  cached_network_image:
  eva_icons_flutter:
  flutter_rating_bar:
  page_indicator:
  font_awesome_flutter:
  image_picker:
  firebase_storage:
  image_picker_android:
  firebase_app_check:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
     - assets/images/logo.png
     - assets/images/pipoca.png
     - assets/fonts/

  fonts:
    - family: BILYALAYEREDBASE
      fonts:
        - asset: assets/fonts/BILYALAYEREDBASE.ttf

